# Generated by Django 5.0.6 on 2024-10-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='turfBooking',
        ),
    ]
