# Generated by Django 5.0.6 on 2024-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0002_delete_turfbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookslot',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.RemoveField(
            model_name='turfbooked',
            name='current_date',
        ),
        migrations.AlterField(
            model_name='turfbooked',
            name='selected_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='turfbooked',
            name='slots',
            field=models.JSONField(default=list),
        ),
    ]
