# Generated by Django 5.0.6 on 2024-12-07 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0003_delete_bookslot_delete_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfbooked',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
