# Generated by Django 5.1.2 on 2024-10-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0006_auto_20211116_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turfbooked',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='turfbooked',
            name='payment_id',
        ),
    ]
